server:
  port: 10081
spring:
  application.name: eba-ai-stdv6-rag
  datasource:
    url: jdbc:mysql://localhost:3306/eba_ai?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${EBA_DB_MYSQL_USER}
    password: ${EBA_DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      api-key: ${EBA_AI_API_KEY}

mybatis-plus:
  global-config:
    db-config:
        id-type: ASSIGN_ID  # id生成规则为雪花算法
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 到控制台（开发用）
    map-underscore-to-camel-case: true  # 开启驼峰命名自动映射
